apiVersion: v2
name: lagoon-gatekeeper
description:
  A Helm chart for Kubernetes that installs the gatekeeper admission controller
  and policy for Lagoon.
home: https://github.com/amazeeio/charts
icon: https://raw.githubusercontent.com/uselagoon/lagoon-charts/main/icon.png
maintainers:
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io

type: application

version: 0.3.0

# appVersion reflects the gatekeeper-library version
appVersion: 2e5e92f

dependencies:
- name: gatekeeper
  repository: https://open-policy-agent.github.io/gatekeeper/charts
  version: ~3.3.0
