{{/*
This somewhat complex logic is intended to:
  * generate a random secret value automatically on chart install
  * not overwrite the randomly generated value on upgrade
  * allow overriding if the value is explicitly defined
*/}}
{{- $data := index (lookup "v1" "Secret" .Release.Namespace (include "lagoon-core.apiDB.fullname" .)) "data" | default dict }}
{{- $apiDBPassword := coalesce .Values.apiDBPassword (ternary (randAlpha 32) (index $data "API_DB_PASSWORD" | default "" | b64dec) (index $data "API_DB_PASSWORD" | empty)) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-core.apiDB.fullname" . }}
  labels:
    {{- include "lagoon-core.apiDB.labels" . | nindent 4 }}
stringData:
{{- if not .Values.apiDB.useExternal }}
  API_DB_PASSWORD: {{ $apiDBPassword | quote }}
  API_DB_HOST: {{ include "lagoon-core.apiDB.fullname" . }}
  API_DB_ADDRESS: {{ include "lagoon-core.apiDB.fullname" . }}
{{- else }}
  API_DB_HOST: {{ required "A valid apiDBHost required!" .Values.apiDBHost }}
  API_DB_PORT: {{ required "A valid apiDBPort required!" .Values.apiDBPort | quote }}
  API_DB_ADDRESS: {{ .Values.apiDBHost }}:{{ .Values.apiDBPort }}
  API_DB_USERNAME: {{ required "A valid apiDBUsername required!" .Values.apiDBUsername }}
  API_DB_PASSWORD: {{ required "A valid apiDBPassword required!" .Values.apiDBPassword | quote }}
  API_DB_DATABASE: {{ required "A valid apiDBDatabase required!" .Values.apiDBDatabase }}
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lagoon-core.apiMigrateDB.fullname" . }}
  labels:
    {{- include "lagoon-core.api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    "helm.sh/hook-weight": "-5"
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "lagoon-core.api.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      securityContext:
          {{- toYaml .Values.api.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: 120
      containers:
      - name: api-migratedb
        args:
        - ./node_modules/.bin/knex migrate:list --cwd /app/services/api/database;
          ./node_modules/.bin/knex migrate:latest --cwd /app/services/api/database
        image: {{ .Values.api.image.repository }}:{{ coalesce .Values.api.image.tag .Values.imageTag .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        securityContext:
          {{- toYaml .Values.api.securityContext | nindent 10 }}
        env:
        {{- if not .Values.apiDB.useExternal }}
        - name: API_DB_PASSWORD
          value: {{ $apiDBPassword | quote }}
        - name: API_DB_HOST
          value: {{ include "lagoon-core.apiDB.fullname" . }}
        {{- else }}
        - name: API_DB_HOST
          value: {{ required "A valid apiDBHost required!" .Values.apiDBHost }}
        - name: API_DB_PORT
          value: {{ required "A valid apiDBPort required!" .Values.apiDBPort | quote }}
        - name: API_DB_USERNAME
          value: {{ required "A valid apiDBUsername required!" .Values.apiDBUsername }}
        - name: API_DB_PASSWORD
          value: {{ required "A valid apiDBPassword required!" .Values.apiDBPassword | quote }}
        - name: API_DB_DATABASE
          value: {{ required "A valid apiDBDatabase required!" .Values.apiDBDatabase }}
        {{- end }}
        - name: LAGOON_VERSION
          value: {{ .Chart.AppVersion | replace "-" "." }}
      {{- range $key, $val := .Values.api.additionalEnvs }}
        - name: {{ $key }}
          value: {{ $val | quote }}
      {{- end }}
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
