{{/*
This somewhat complex logic is intended to:
  * generate a random secret value automatically on chart install
  * not overwrite the randomly generated value on upgrade
  * allow overriding if the value is explicitly defined
*/}}
{{- $data := index (lookup "v1" "Secret" .Release.Namespace (include "lagoon-core.apiDB.fullname" .)) "data" | default dict }}
{{- $apiDBPassword := coalesce .Values.apiDBPassword (ternary (randAlpha 32) (index $data "API_DB_PASSWORD" | default "" | b64dec) (index $data "API_DB_PASSWORD" | empty)) }}
{{- $apiDBHost := coalesce .Values.apiDBHost (include "lagoon-core.apiDB.fullname" .) }}
{{- $apiDBPort := coalesce .Values.apiDBPort .Values.apiDB.service.port }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-core.apiDB.fullname" . }}
  labels:
    {{- include "lagoon-core.apiDB.labels" . | nindent 4 }}
stringData:
  API_DB_HOST: {{ $apiDBHost }}
  API_DB_PORT: {{ $apiDBPort | quote }}
  API_DB_ADDRESS: {{ $apiDBHost }}:{{ $apiDBPort }}
  API_DB_USERNAME: {{ .Values.apiDBUsername }}
  API_DB_PASSWORD: {{ $apiDBPassword | quote }}
  API_DB_DATABASE: {{ .Values.apiDBDatabase }}
