apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-core.apiDB.fullname" . }}
  labels:
    {{- include "lagoon-core.apiDB.labels" . | nindent 4 }}
stringData:
{{- if not .Values.apiDB.useExternal }}
{{/*
This somewhat complex logic is intended to:
  * generate a random secret value automatically on chart install
  * not overwrite the randomly generated value on upgrade
  * allow overriding if the value is explicitly defined
*/}}
{{- $data := index (lookup "v1" "Secret" .Release.Namespace (include "lagoon-core.apiDB.fullname" .)) "data" | default dict }}
{{- $apiDBPassword := coalesce .Values.apiDBPassword (ternary (randAlpha 32) (index $data "API_DB_PASSWORD" | default "" | b64dec) (index $data "API_DB_PASSWORD" | empty)) }}
  API_DB_PASSWORD: {{ $apiDBPassword | quote }}
  API_DB_HOST: {{ include "lagoon-core.apiDB.fullname" . }}
  API_DB_ADDRESS: {{ include "lagoon-core.apiDB.fullname" . }}
{{- else }}
  API_DB_HOST: {{ required "A valid apiDBHost required!" .Values.apiDBHost }}
  API_DB_PORT: {{ required "A valid apiDBPort required!" .Values.apiDBPort | quote }}
  API_DB_ADDRESS: {{ .Values.apiDBHost }}:{{ .Values.apiDBPort }}
  API_DB_USERNAME: {{ required "A valid apiDBUsername required!" .Values.apiDBUsername }}
  API_DB_PASSWORD: {{ required "A valid apiDBPassword required!" .Values.apiDBPassword | quote }}
  API_DB_DATABASE: {{ required "A valid apiDBDatabase required!" .Values.apiDBDatabase }}
{{- end }}
