{{- if .Values.sshPortal.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-core.sshPortal.fullname" . }}
  labels:
    {{- include "lagoon-core.sshPortal.labels" . | nindent 4 }}
spec:
{{- if not .Values.sshPortal.autoscaling.enabled }}
  replicas: {{ .Values.sshPortal.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "lagoon-core.sshPortal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/ssh-portal.secret: {{ include (print $.Template.BasePath "/ssh-portal.secret.yaml") . | sha256sum }}
    {{- with .Values.sshPortal.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-core.sshPortal.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lagoon-core.sshPortal.serviceAccountName" . }}
      securityContext:
        {{- toYaml (coalesce .Values.sshPortal.podSecurityContext .Values.podSecurityContext) | nindent 8 }}
      containers:
      - name: ssh-portal
        securityContext:
          {{- toYaml .Values.sshPortal.securityContext | nindent 10 }}
        image: "{{ .Values.sshPortal.image.repository }}:{{ coalesce .Values.sshPortal.image.tag .Values.imageTag .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.sshPortal.image.pullPolicy }}
        command:
        - "/ssh-portal"
        {{- if .Values.sshPortal.debug }}
        - "--debug"
        {{- end }}
        env:
        - name: KEYCLOAK_BASEURL
          value: http://{{ include "lagoon-core.keycloak.fullname" . }}:{{ .Values.keycloak.service.port }}/
        - name: KEYCLOAK_AUTH_SERVER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.keycloak.fullname" . }}
              key: KEYCLOAK_AUTH_SERVER_CLIENT_SECRET
        - name: GRAPHQL_ENDPOINT
          value: http://{{ include "lagoon-core.api.fullname" . }}:{{ .Values.api.service.port }}/graphql
        - name: JWTSECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.fullname" . }}-jwtsecret
              key: JWTSECRET
        - name: HOSTKEY_RSA
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.sshPortal.fullname" . }}
              key: HOSTKEY_RSA
        - name: HOSTKEY_ED25519
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.sshPortal.fullname" . }}
              key: HOSTKEY_ED25519
      {{- range $key, $val := .Values.sshPortal.additionalEnvs }}
        - name: {{ $key }}
          value: {{ $val | quote }}
      {{- end }}
        ports:
        - name: ssh
          containerPort: 2222
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: ssh
        readinessProbe:
          tcpSocket:
            port: ssh
        resources:
          {{- toYaml .Values.ssh.resources | nindent 10 }}
      {{- with .Values.ssh.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "lagoon-core.name" . }}
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - {{ include "lagoon-core.sshPortal.fullname" . }}
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- with .Values.sshPortal.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sshPortal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
