{{- if .Values.storageCalculator.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-core.storageCalculator.fullname" . }}
  labels:
    {{- include "lagoon-core.storageCalculator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lagoon-core.storageCalculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    {{- with .Values.storageCalculator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-core.storageCalculator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (coalesce .Values.storageCalculator.podSecurityContext .Values.podSecurityContext) | nindent 8 }}
      containers:
      - name: storage-calculator
        securityContext:
          {{- toYaml .Values.storageCalculator.securityContext | nindent 10 }}
        image: "{{ .Values.storageCalculator.image.repository }}:{{ coalesce .Values.storageCalculator.image.tag .Values.imageTag .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.storageCalculator.image.pullPolicy }}
        env:
        - name: JWTSECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.fullname" . }}-jwtsecret
              key: JWTSECRET
        - name: GRAPHQL_ENDPOINT
          value: http://{{ include "lagoon-core.api.fullname" . }}:{{ .Values.api.service.port }}/graphql
        - name: CRONJOBS
          value: |-
            5 */12 * * * /lagoon/cronjob.sh /calculate-storage.sh
      {{- range $key, $val := .Values.storageCalculator.additionalEnvs }}
        - name: {{ $key }}
          value: {{ $val | quote }}
      {{- end }}
        resources:
          {{- toYaml .Values.storageCalculator.resources | nindent 10 }}
      {{- with .Values.storageCalculator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.storageCalculator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.storageCalculator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
