apiVersion: v2
name: lagoon-test
description: A Helm chart for Kubernetes which runs the Lagoon test suite.
home: https://github.com/uselagoon/lagoon-charts
icon: https://raw.githubusercontent.com/uselagoon/lagoon-charts/main/icon.png
maintainers:
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io
kubeVersion: ">= 1.19.0-0"

type: application

version: 1.0.0

appVersion: main
