apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lagoon-test.fullname" . }}
  labels:
    {{- include "lagoon-test.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-test.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
